"""Added_login_index

Revision ID: 95cbd3bcced3
Revises: d6299e215ba7
Create Date: 2025-12-22 15:05:34.571982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cbd3bcced3'
down_revision: Union[str, Sequence[str], None] = 'd6299e215ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_login', 'users', ['login'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_login', table_name='users')
    # ### end Alembic commands ###
