"""Added_hashad_fields

Revision ID: e66bc8c33d81
Revises: d1fd8c37c22f
Create Date: 2025-11-01 20:04:17.850653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66bc8c33d81'
down_revision: Union[str, Sequence[str], None] = 'd1fd8c37c22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('encrypted_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_hash', sa.String(), nullable=True))
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'email_hash')
    op.drop_column('users', 'encrypted_email')
    op.drop_column('users', 'phone_number_hash')
    op.drop_column('users', 'encrypted_phone_number')
    # ### end Alembic commands ###
