"""added_unique_mark

Revision ID: d6299e215ba7
Revises: e66bc8c33d81
Create Date: 2025-11-02 20:16:24.034055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6299e215ba7'
down_revision: Union[str, Sequence[str], None] = 'e66bc8c33d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['encrypted_email'])
    op.create_unique_constraint(None, 'users', ['email_hash'])
    op.create_unique_constraint(None, 'users', ['phone_number_hash'])
    op.create_unique_constraint(None, 'users', ['encrypted_phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
