# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/gRPC/protos/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/gRPC/protos/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asrc/gRPC/protos/user.proto\"1\n\x19GetUserInfoByTokenRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"7\n\x1aGetUserInfoByTokenResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\"&\n\x15GetUserByLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\"3\n\x16GetUserByLoginResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetUserByIdResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t2\xd8\x01\n\x04User\x12O\n\x12GetUserInfoByToken\x12\x1a.GetUserInfoByTokenRequest\x1a\x1b.GetUserInfoByTokenResponse\"\x00\x12\x43\n\x0eGetUserByLogin\x12\x16.GetUserByLoginRequest\x1a\x17.GetUserByLoginResponse\"\x00\x12:\n\x0bGetUserById\x12\x13.GetUserByIdRequest\x1a\x14.GetUserByIdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.gRPC.protos.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERINFOBYTOKENREQUEST']._serialized_start=30
  _globals['_GETUSERINFOBYTOKENREQUEST']._serialized_end=79
  _globals['_GETUSERINFOBYTOKENRESPONSE']._serialized_start=81
  _globals['_GETUSERINFOBYTOKENRESPONSE']._serialized_end=136
  _globals['_GETUSERBYLOGINREQUEST']._serialized_start=138
  _globals['_GETUSERBYLOGINREQUEST']._serialized_end=176
  _globals['_GETUSERBYLOGINRESPONSE']._serialized_start=178
  _globals['_GETUSERBYLOGINRESPONSE']._serialized_end=229
  _globals['_GETUSERBYIDREQUEST']._serialized_start=231
  _globals['_GETUSERBYIDREQUEST']._serialized_end=263
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=265
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=313
  _globals['_USER']._serialized_start=316
  _globals['_USER']._serialized_end=532
# @@protoc_insertion_point(module_scope)
