server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;

    root /data;

    location = /auth/api/v1/users/login {
        limit_req zone=login_limit burst=3 nodelay;
        limit_req_status 429;
        proxy_pass http://nginx_auth;
    }
    location = /auth/api/v1/users/signup {
        limit_req zone=signup_limit burst=2 nodelay;
        limit_req_status 429;
        proxy_pass http://nginx_auth;
    }
    location /auth/ {
        proxy_pass http://nginx_auth;
    }
    location /messenger/ {
        proxy_pass http://nginx_messenger;
    }
    location /web/ {
        alias /data/web/;
        index index.html;
    }
    location = / {
        return 302 /web/;
    }
    location / {
        return 404;
    }

    error_page   404              /404.html;
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}
