services:
  nginx_gateway:
    container_name: nginx_gateway
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./infra/configs/nginx_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/configs/nginx_gateway/site.conf:/etc/nginx/conf.d/site.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - ../web:/data/web:ro
    ports:
      - "0.0.0.0:80:80"  # доступ с других устройств в сети по http://<IP_хоста>
